# Generated by Django 5.1 on 2024-08-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todoo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoo",
            name="status",
            field=models.CharField(
                choices=[("doing", "In Progress"), ("done", "Done")],
                default="doing",
                max_length=250,
            ),
        ),
    ]
